@SoftwareServicePlatform.Api_HostAddress = http://localhost:5108

GET {{SoftwareServicePlatform.Api_HostAddress}}/weatherforecast/
Accept: application/json


### 查询客户
GET {{SoftwareServicePlatform.Api_HostAddress}}/api/customers
Accept: application/json


### 新增客户
POST {{SoftwareServicePlatform.Api_HostAddress}}/api/customers
Content-Type: application/json

{
  "name": "cwb"
}

### 修改用户
PUT http://localhost:5108/api/Customers/2
Content-Type:application/json
{
  "id":2,
   "name": "武汉道路检测有限公司"
}

### 删除客户
DELETE http://localhost:5108/api/customers/1

### 获取软件列表
GET http://localhost:5108/api/softwares
Accept: application/json

### 新增软件

POST http://localhost:5108/api/softwares
Content-Type: application/json

{
  "name": "路面检测数据处理软件",
  "code": "ROAD_PROCESS",
  "shortName": "道路处理平台",
  "category": "道路检测",
  "description": "用于道路检测数据导入、处理、统计及结果导出。",
  "developer": "张三",
  "supportOwner": "李四",
  "department": "研发部",
  "platform": "Windows",
  "technologyStack": "C++ / Qt",
  "isEnabled": true,
  "allowDownload": true,
  "remark": "核心业务软件"
}


### 修改软件

PUT http://localhost:5108/api/softwares/1
Content-Type: application/json

{
  "id": 1,
  "name": "路面智能检测数据处理软件",
  "code": "ROAD_PROCESS",
  "shortName": "道路处理平台",
  "category": "道路检测",
  "description": "用于道路检测数据处理、统计分析以及结果导出。",
  "developer": "张三",
  "supportOwner": "王工",
  "department": "研发部",
  "platform": "Windows",
  "technologyStack": "C++ / Qt",
  "isEnabled": true,
  "allowDownload": true,
  "remark": "核心业务软件"
}

  ### 新增删除测试软件

POST http://localhost:5108/api/softwares
Content-Type: application/json

{
  "name": "删除测试软件",
  "code": "DELETE_TEST",
  "shortName": "测试",
  "category": "测试",
  "description": "",
  "developer": "",
  "supportOwner": "",
  "department": "",
  "platform": "Windows",
  "technologyStack": "",
  "isEnabled": true,
  "allowDownload": false,
  "remark": ""
}
### 删除软件

DELETE http://localhost:5108/api/softwares/2

### 获得软件版本表
GET http://localhost:5108/api/softwareversions

### 添加版本
POST http://localhost:5108/api/softwareversions
Content-Type: application/json

{
  "softwareId": 1,
  "version": "1.0.0",
  "versionType": "Release",
  "title": "首个正式版本",
  "releaseNotes": "首次发布",
  "isPublished": true,
  "forceUpdate": false,
  "allowDownload": true
}

### 客户软件信息绑定
POST http://localhost:5108/api/customersoftwares
Content-Type: application/json
{
  "customerId": 9,
  "softwareId": 1,
  "remark": "测试绑定"
}
### 获取客户信息
GET http://localhost:5108/api/customersoftwares?customerId=1