@SoftwareServicePlatform.Api_HostAddress = http://localhost:5108
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImRpc3BsYXlOYW1lIjoiYWRtaW4iLCJjdXN0b21lcklkIjoiOSIsIm5iZiI6MTc4OTA5NTI2MCwiZXhwIjoxNzg5MTAyNDYwLCJpc3MiOiJTb2Z0d2FyZVNlcnZpY2VQbGF0Zm9ybSIsImF1ZCI6IlNvZnR3YXJlU2VydmljZVBsYXRmb3JtLkNsaWVudCJ9.NydQhArQl6je0yftwCmAFjtmI_Cu5UIcadhFjWLu8Eg

GET {{SoftwareServicePlatform.Api_HostAddress}}/weatherforecast/
Accept: application/json


### 查询客户
GET {{SoftwareServicePlatform.Api_HostAddress}}/api/customers
Accept: application/json


### 新增客户
POST {{SoftwareServicePlatform.Api_HostAddress}}/api/customers
Content-Type: application/json

{
  "name": "cwb"
}

### 修改用户
PUT http://localhost:5108/api/Customers/2
Content-Type:application/json
{
  "id":2,
   "name": "武汉道路检测有限公司"
}

### 删除客户
DELETE http://localhost:5108/api/customers/1

### 获取软件列表
GET http://localhost:5108/api/softwares
Accept: application/json

### 新增软件

POST http://localhost:5108/api/softwares
Content-Type: application/json

{
  "name": "路面检测数据处理软件",
  "code": "ROAD_PROCESS",
  "shortName": "道路处理平台",
  "category": "道路检测",
  "description": "用于道路检测数据导入、处理、统计及结果导出。",
  "developer": "张三",
  "supportOwner": "李四",
  "department": "研发部",
  "platform": "Windows",
  "technologyStack": "C++ / Qt",
  "isEnabled": true,
  "allowDownload": true,
  "remark": "核心业务软件"
}


### 修改软件

PUT http://localhost:5108/api/softwares/1
Content-Type: application/json

{
  "id": 1,
  "name": "路面智能检测数据处理软件",
  "code": "ROAD_PROCESS",
  "shortName": "道路处理平台",
  "category": "道路检测",
  "description": "用于道路检测数据处理、统计分析以及结果导出。",
  "developer": "张三",
  "supportOwner": "王工",
  "department": "研发部",
  "platform": "Windows",
  "technologyStack": "C++ / Qt",
  "isEnabled": true,
  "allowDownload": true,
  "remark": "核心业务软件"
}

  ### 新增删除测试软件

POST http://localhost:5108/api/softwares
Content-Type: application/json

{
  "name": "删除测试软件",
  "code": "DELETE_TEST",
  "shortName": "测试",
  "category": "测试",
  "description": "",
  "developer": "",
  "supportOwner": "",
  "department": "",
  "platform": "Windows",
  "technologyStack": "",
  "isEnabled": true,
  "allowDownload": false,
  "remark": ""
}
### 删除软件

DELETE http://localhost:5108/api/softwares/2

### 获得软件版本表
GET http://localhost:5108/api/softwareversions

### 添加版本
POST http://localhost:5108/api/softwareversions
Content-Type: application/json

{
  "softwareId": 1,
  "version": "1.0.0",
  "versionType": "Release",
  "title": "首个正式版本",
  "releaseNotes": "首次发布",
  "isPublished": true,
  "forceUpdate": false,
  "allowDownload": true
}


### 注册账户
POST http://localhost:5108/api/auth/register
Content-Type: application/json

{
  "username": "cwb",
  "password": "12345678",
  "displayName": "cwb",
  "email": "testuser@example.com",
  "phone": "13800138000",
  "customerId": 12
} 

### 登录账户
POST http://localhost:5108/api/auth/login
Content-Type: application/json

{
  "username": "cwb",
  "password": "12345678"
} 
### 登录账户
POST http://localhost:5108/api/auth/login
Content-Type: application/json

{
  "username": "developer01",
  "password": "12345678"
} 
###jwt验证get
GET http://localhost:5108/api/auth/me
Authorization: Bearer


###下载
GET http://localhost:5108/api/softwareversions/1/package/download
Authorization: Bearer {{token}}

### 注册管理员账户
POST http://localhost:5108/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "12345678",
  "displayName": "admin",
  "email": "testuser@example.com",
  "phone": "13800138000",
  "customerId": 9
} 

### 登录管理员账户
POST http://localhost:5108/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456789"
} 

###获取用户列表
GET http://localhost:5108/api/users
Authorization: Bearer {{token}}


### 创建开发人员账户
POST http://localhost:5108/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "developer01",
  "password": "12345678",
  "displayName": "测试开发人员",
  "role": "Developer",
  "email": "developer@example.com",
  "phone": "13800138000"
}

### 修改账户
PUT http://localhost:5108/api/users/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "displayName": "李工",
  "role": "Support",
  "email": "ligong@example.com",
  "phone": "13800138001",
  "isEnabled": false
}

### 创建工单

POST http://localhost:5108/api/tickets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "softwareId": 1,
  "title": "软件启动后提示数据库连接失败",
  "description": "双击软件启动后提示数据库连接失败，目前无法进入主界面。",
  "priority": "High"
}


### Customer 查询工单

GET http://localhost:5108/api/tickets
Authorization: Bearer {{token}}


### Admin 分配工单

PUT http://localhost:5108/api/tickets/1/assign
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "assignedToUserId": 4
}

### 登录管理员账户
POST http://localhost:5108/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456789"
} 

### Admin 第一次分配工单

PUT http://localhost:5108/api/tickets/1/assign
Authorization: Bearer {{token}} 
Content-Type: application/json

{
  "assignedToUserId": 4
}