using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SoftwareServicePlatform.Api.Migrations
{
    /// <inheritdoc />
    public partial class AdoptClientUpdateCredentialsIntoEf : Migration
    {
        /// <inheritdoc />
        protected override void Up(
            MigrationBuilder migrationBuilder)
        {
            /*
             * ClientUpdateCredentials 以前由程序运行时通过：
             *
             * CREATE TABLE IF NOT EXISTS
             *
             * 创建。
             *
             * 因此：
             *
             * 1. 老数据库中，这张表可能已经存在；
             * 2. 新数据库中，这张表可能不存在。
             *
             * 本 Migration 必须兼容这两种情况，
             * 不能直接使用 migrationBuilder.CreateTable，
             * 否则老数据库会报：
             *
             * relation "ClientUpdateCredentials" already exists
             */


            /*
             * ==========================================
             * 1. 表不存在时创建
             * ==========================================
             */
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "ClientUpdateCredentials"
                (
                    "Id" integer
                        GENERATED BY DEFAULT AS IDENTITY
                        NOT NULL,

                    "CustomerSoftwareId" integer NOT NULL,

                    "TokenHash"
                        character varying(64)
                        NOT NULL,

                    "TokenPrefix"
                        character varying(64)
                        NOT NULL,

                    "IsEnabled"
                        boolean
                        NOT NULL,

                    "CreatedAt"
                        timestamp with time zone
                        NOT NULL,

                    "UpdatedAt"
                        timestamp with time zone
                        NOT NULL,

                    "LastUsedAt"
                        timestamp with time zone
                        NULL,

                    CONSTRAINT
                        "PK_ClientUpdateCredentials"
                        PRIMARY KEY ("Id"),

                    CONSTRAINT
                        "FK_ClientUpdateCredentials_CustomerSoftwares_CustomerSoftwareId"
                        FOREIGN KEY ("CustomerSoftwareId")
                        REFERENCES "CustomerSoftwares" ("Id")
                        ON DELETE CASCADE
                );
                """
            );


            /*
             * ==========================================
             * 2. 兼容以前手工创建的主键名称
             * ==========================================
             *
             * 以前：
             *
             * PRIMARY KEY
             *
             * 没有显式指定主键名称，
             * PostgreSQL 通常会生成：
             *
             * ClientUpdateCredentials_pkey
             *
             * EF Core 期望：
             *
             * PK_ClientUpdateCredentials
             *
             * 为了避免以后 EF Migration 修改主键时
             * 找不到约束，这里统一名称。
             */
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE
                            conname =
                            'ClientUpdateCredentials_pkey'
                    )
                    AND NOT EXISTS
                    (
                        SELECT 1
                        FROM pg_constraint
                        WHERE
                            conname =
                            'PK_ClientUpdateCredentials'
                    )
                    THEN
                        ALTER TABLE
                            "ClientUpdateCredentials"
                        RENAME CONSTRAINT
                            "ClientUpdateCredentials_pkey"
                        TO
                            "PK_ClientUpdateCredentials";
                    END IF;
                END
                $$;
                """
            );


            /*
             * ==========================================
             * 3. CustomerSoftwareId 唯一索引
             * ==========================================
             */
            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS
                    "IX_ClientUpdateCredentials_CustomerSoftwareId"
                ON
                    "ClientUpdateCredentials"
                    ("CustomerSoftwareId");
                """
            );


            /*
             * ==========================================
             * 4. TokenHash 唯一索引
             * ==========================================
             */
            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS
                    "IX_ClientUpdateCredentials_TokenHash"
                ON
                    "ClientUpdateCredentials"
                    ("TokenHash");
                """
            );
        }


        /// <inheritdoc />
        protected override void Down(
            MigrationBuilder migrationBuilder)
        {
            /*
             * 不在 Down 中删除 ClientUpdateCredentials。
             *
             * 原因：
             *
             * 这张表在纳入 EF Migration 以前
             * 就已经可能存在并包含真实客户端 Token。
             *
             * 如果这里 DropTable，
             * 一次误回滚就可能把所有客户端更新凭证删除。
             *
             * 因此 adoption migration 的回滚
             * 选择保留原有业务数据。
             */
        }
    }
}