using System.Data;
using System.Data.Common;
using Microsoft.EntityFrameworkCore;
using SoftwareServicePlatform.Api.Data;

namespace SoftwareServicePlatform.Api.Services.ClientUpdates
{
    /// <summary>
    /// 客户端更新凭证存储。
    ///
    /// 为了让本功能可以直接覆盖到你当前工程中，
    /// 不要求你手工修改 EF Migration / Snapshot，
    /// 这一张独立的小表在第一次使用时通过 PostgreSQL
    /// CREATE TABLE IF NOT EXISTS 自动创建。
    ///
    /// 其它业务表仍然继续由 EF Core 正常管理。
    ///
    /// 将来如果你希望完全纳入 EF Migration，
    /// 可以再把这张表迁移成标准 Entity + Migration。
    /// </summary>
    public sealed class ClientUpdateCredentialStore
    {
        private readonly AppDbContext
            _dbContext;


        public ClientUpdateCredentialStore(
            AppDbContext dbContext)
        {
            _dbContext =
                dbContext;
        }


        /// <summary>
        /// 确保更新凭证表存在。
        ///
        /// PostgreSQL 中：
        ///
        /// CustomerSoftwareId 唯一，
        /// 代表一个“客户 + 软件”只保留一套有效凭证记录。
        /// </summary>
        public async Task EnsureTableAsync(
            CancellationToken cancellationToken = default)
        {
            var sql =
                """
                CREATE TABLE IF NOT EXISTS "ClientUpdateCredentials"
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "CustomerSoftwareId" integer NOT NULL,
                    "TokenHash" character varying(64) NOT NULL,
                    "TokenPrefix" character varying(64) NOT NULL,
                    "IsEnabled" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    "LastUsedAt" timestamp with time zone NULL,

                    CONSTRAINT "FK_ClientUpdateCredentials_CustomerSoftwares_CustomerSoftwareId"
                        FOREIGN KEY ("CustomerSoftwareId")
                        REFERENCES "CustomerSoftwares" ("Id")
                        ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS
                    "IX_ClientUpdateCredentials_CustomerSoftwareId"
                ON "ClientUpdateCredentials" ("CustomerSoftwareId");

                CREATE UNIQUE INDEX IF NOT EXISTS
                    "IX_ClientUpdateCredentials_TokenHash"
                ON "ClientUpdateCredentials" ("TokenHash");
                """;

            await _dbContext.Database
                .ExecuteSqlRawAsync(
                    sql,
                    cancellationToken
                );
        }


        public async Task<
            List<ClientUpdateCredentialRecord>>
            GetAllAsync(
                CancellationToken cancellationToken =
                    default)
        {
            await EnsureTableAsync(
                cancellationToken
            );

            return await QueryAsync(
                """
                SELECT
                    "Id",
                    "CustomerSoftwareId",
                    "TokenHash",
                    "TokenPrefix",
                    "IsEnabled",
                    "CreatedAt",
                    "UpdatedAt",
                    "LastUsedAt"
                FROM "ClientUpdateCredentials"
                ORDER BY "CustomerSoftwareId";
                """,
                parameters: null,
                cancellationToken
            );
        }


        public async Task<
            ClientUpdateCredentialRecord?>
            GetByCustomerSoftwareIdAsync(
                int customerSoftwareId,
                CancellationToken cancellationToken =
                    default)
        {
            await EnsureTableAsync(
                cancellationToken
            );

            var rows =
                await QueryAsync(
                    """
                    SELECT
                        "Id",
                        "CustomerSoftwareId",
                        "TokenHash",
                        "TokenPrefix",
                        "IsEnabled",
                        "CreatedAt",
                        "UpdatedAt",
                        "LastUsedAt"
                    FROM "ClientUpdateCredentials"
                    WHERE "CustomerSoftwareId" = @bindingId
                    LIMIT 1;
                    """,
                    new Dictionary<
                        string,
                        object?>
                    {
                        ["@bindingId"] =
                            customerSoftwareId
                    },
                    cancellationToken
                );

            return rows
                .FirstOrDefault();
        }


        public async Task<
            ClientUpdateCredentialRecord?>
            GetByTokenHashAsync(
                string tokenHash,
                CancellationToken cancellationToken =
                    default)
        {
            await EnsureTableAsync(
                cancellationToken
            );

            var rows =
                await QueryAsync(
                    """
                    SELECT
                        "Id",
                        "CustomerSoftwareId",
                        "TokenHash",
                        "TokenPrefix",
                        "IsEnabled",
                        "CreatedAt",
                        "UpdatedAt",
                        "LastUsedAt"
                    FROM "ClientUpdateCredentials"
                    WHERE "TokenHash" = @tokenHash
                    LIMIT 1;
                    """,
                    new Dictionary<
                        string,
                        object?>
                    {
                        ["@tokenHash"] =
                            tokenHash
                    },
                    cancellationToken
                );

            return rows
                .FirstOrDefault();
        }


        /// <summary>
        /// 第一次生成 Token 时 INSERT；
        /// 重置 Token 时覆盖原 Hash，并重新启用。
        /// </summary>
        public async Task UpsertAsync(
            int customerSoftwareId,
            string tokenHash,
            string tokenPrefix,
            CancellationToken cancellationToken =
                default)
        {
            await EnsureTableAsync(
                cancellationToken
            );

            var now =
                DateTime.UtcNow;

            await ExecuteAsync(
                """
                INSERT INTO "ClientUpdateCredentials"
                (
                    "CustomerSoftwareId",
                    "TokenHash",
                    "TokenPrefix",
                    "IsEnabled",
                    "CreatedAt",
                    "UpdatedAt",
                    "LastUsedAt"
                )
                VALUES
                (
                    @bindingId,
                    @tokenHash,
                    @tokenPrefix,
                    TRUE,
                    @now,
                    @now,
                    NULL
                )
                ON CONFLICT ("CustomerSoftwareId")
                DO UPDATE SET
                    "TokenHash" = EXCLUDED."TokenHash",
                    "TokenPrefix" = EXCLUDED."TokenPrefix",
                    "IsEnabled" = TRUE,
                    "UpdatedAt" = EXCLUDED."UpdatedAt",
                    "LastUsedAt" = NULL;
                """,
                new Dictionary<
                    string,
                    object?>
                {
                    ["@bindingId"] =
                        customerSoftwareId,

                    ["@tokenHash"] =
                        tokenHash,

                    ["@tokenPrefix"] =
                        tokenPrefix,

                    ["@now"] =
                        now
                },
                cancellationToken
            );
        }


        public async Task SetEnabledAsync(
            int customerSoftwareId,
            bool enabled,
            CancellationToken cancellationToken =
                default)
        {
            await EnsureTableAsync(
                cancellationToken
            );

            await ExecuteAsync(
                """
                UPDATE "ClientUpdateCredentials"
                SET
                    "IsEnabled" = @enabled,
                    "UpdatedAt" = @now
                WHERE
                    "CustomerSoftwareId" = @bindingId;
                """,
                new Dictionary<
                    string,
                    object?>
                {
                    ["@enabled"] =
                        enabled,

                    ["@now"] =
                        DateTime.UtcNow,

                    ["@bindingId"] =
                        customerSoftwareId
                },
                cancellationToken
            );
        }


        public async Task TouchLastUsedAsync(
            int credentialId,
            CancellationToken cancellationToken =
                default)
        {
            await EnsureTableAsync(
                cancellationToken
            );

            await ExecuteAsync(
                """
                UPDATE "ClientUpdateCredentials"
                SET "LastUsedAt" = @now
                WHERE "Id" = @id;
                """,
                new Dictionary<
                    string,
                    object?>
                {
                    ["@now"] =
                        DateTime.UtcNow,

                    ["@id"] =
                        credentialId
                },
                cancellationToken
            );
        }


        private async Task<
            List<ClientUpdateCredentialRecord>>
            QueryAsync(
                string sql,
                Dictionary<string, object?>?
                    parameters,
                CancellationToken cancellationToken)
        {
            var connection =
                _dbContext.Database
                    .GetDbConnection();

            var shouldClose =
                connection.State
                != ConnectionState.Open;

            if (shouldClose)
            {
                await connection.OpenAsync(
                    cancellationToken
                );
            }

            try
            {
                await using var command =
                    connection.CreateCommand();

                command.CommandText =
                    sql;

                AddParameters(
                    command,
                    parameters
                );

                var rows =
                    new List<
                        ClientUpdateCredentialRecord>();

                await using var reader =
                    await command
                        .ExecuteReaderAsync(
                            cancellationToken
                        );

                while (
                    await reader.ReadAsync(
                        cancellationToken)
                )
                {
                    rows.Add(
                        new ClientUpdateCredentialRecord
                        {
                            Id =
                                reader
                                    .GetInt32(0),

                            CustomerSoftwareId =
                                reader
                                    .GetInt32(1),

                            TokenHash =
                                reader
                                    .GetString(2),

                            TokenPrefix =
                                reader
                                    .GetString(3),

                            IsEnabled =
                                reader
                                    .GetBoolean(4),

                            CreatedAt =
                                reader
                                    .GetDateTime(5),

                            UpdatedAt =
                                reader
                                    .GetDateTime(6),

                            LastUsedAt =
                                reader.IsDBNull(7)
                                    ? null
                                    : reader
                                        .GetDateTime(7)
                        }
                    );
                }

                return rows;
            }
            finally
            {
                if (shouldClose)
                {
                    await connection.CloseAsync();
                }
            }
        }


        private async Task ExecuteAsync(
            string sql,
            Dictionary<string, object?>?
                parameters,
            CancellationToken cancellationToken)
        {
            var connection =
                _dbContext.Database
                    .GetDbConnection();

            var shouldClose =
                connection.State
                != ConnectionState.Open;

            if (shouldClose)
            {
                await connection.OpenAsync(
                    cancellationToken
                );
            }

            try
            {
                await using var command =
                    connection.CreateCommand();

                command.CommandText =
                    sql;

                AddParameters(
                    command,
                    parameters
                );

                await command
                    .ExecuteNonQueryAsync(
                        cancellationToken
                    );
            }
            finally
            {
                if (shouldClose)
                {
                    await connection.CloseAsync();
                }
            }
        }


        private static void AddParameters(
            DbCommand command,
            Dictionary<string, object?>?
                parameters)
        {
            if (parameters == null)
            {
                return;
            }

            foreach (
                var item
                in parameters)
            {
                var parameter =
                    command
                        .CreateParameter();

                parameter.ParameterName =
                    item.Key;

                parameter.Value =
                    item.Value
                    ?? DBNull.Value;

                command.Parameters
                    .Add(parameter);
            }
        }
    }
}
